create table if not exists users
(
    id bigint generated always as identity primary key not null,
    email varchar unique not null,
    username varchar not null,
    nickname varchar,
    password varchar not null,
    role varchar not null,
    status varchar not null
);

create table if not exists posts
(
    id bigint generated always as identity primary key not null,
    author_id bigint not null references users (id),
    creation_date timestamp without time zone,
    description varchar not null,
    photo_url varchar not null
);

create table if not exists followers
(
    id bigint generated by default as identity primary key,
    author_id bigint references users (id),
    follower_id bigint references users (id)
);